<a href="https://colab.research.google.com/github/alxogm/HIGI2022/blob/main/python/python_basico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Típicamente en las primeras celdas se importan las librerias que se utilizarán en el cuaderno. 
import os
import numpy as np 
import matplotlib.pyplot as plt
import math as math

# Este cuaderno de colab, similar a un cuaderno de jupyter, es una introducción a programación en python.

In [2]:
#Esta es una celda de calculo con un comentario

Esta es una celda de texto

El uso mas simple de python es como una calculadora.

In [3]:
2+2

4

In [4]:
4*10

40

In [5]:
5*25+5

130

Cómo en cualquier calculadora, y lenguaje de programación, es importante considerar la jerarquía de operaciones. 

In [6]:
5*(25+5)

150

In [7]:
-2**2

-4

In [8]:
(-2)**2

4

In [9]:
#Si realizas operaciones con numeros escalares, no arreglos o vectores, entonces puedes utilizar la libreria math. 

In [10]:
math.exp(math.log(1))

1.0

In [11]:
math.cos(math.pi)

-1.0

A diferencia de otros lenguajes de programación, la declaración de variables se puede hacer en cualquier celda, y solo se requiere asignar un valor a una variable para que ésta quede definida.

In [12]:
a=5
b=3
c=a*b
print(c)

15


In [13]:
#verifiquemos el tipo de variable que se definió
type(a),type(b),type(c)

(int, int, int)

In [14]:
#Si, uno de los numeros es flotante, la operación resultante será flotante

a=5.
b=3
c=a*b
type(a),type(b),type(c)

(float, int, float)

In [15]:
#La división siempre devuelve un flotante
a=5
b=3
c=a/b
type(a),type(b),type(c)

(int, int, float)

In [16]:
a//b #división descartando la parte fraccional

1

In [17]:
8%3 # El operador % regresa el restante de la división

2

In [18]:
#cuando una variable no está definida e intentamos usarla, nos arroja un error que dice que "la variable no está definida"
n

NameError: ignored

# Listas

Las listas pueden contener elementos de diferentes tipos, aunque tipicamente contienen elementos del mismo tipo

In [19]:
mixta= [1,'texto', 3.0,math.pi]

In [20]:
cuadrados= [1, 4, 9, 16, 25]

In [21]:
#Podemos acceder a cada elemento con su indice, los indices inician en cero. 
print(cuadrados[0])
print(cuadrados[4])
print(cuadrados[-2],cuadrados[3]) 

1
25
16 16


In [22]:
#Dos cadenas pueden concatenarse
cuadrados + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [23]:
#Podemos modificar cada elemento de la lista de forma independiente
cubos = [1, 8, 27, 65, 125]
cubos[3]=4**3
cubos 

[1, 8, 27, 64, 125]

In [24]:
#Podemos añadir nuevos elementos a la lista
cubos.append(6**3)
cubos

[1, 8, 27, 64, 125, 216]

In [25]:
#Podemos accesar y/o modificar la lista por secciones 
letras = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
letras


['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [26]:
letras[2:5] = ['C', 'D', 'E']
letras

['a', 'b', 'C', 'D', 'E', 'f', 'g']

In [27]:
#¿Cuantos elementos tiene la lista?
len(letras)

7

In [28]:
#Es posible tener listas que contienen otras listas
lista=[cuadrados,cubos]
lista

[[1, 4, 9, 16, 25], [1, 8, 27, 64, 125, 216]]

# Funciones de Control

### Ciclo While

In [29]:
a, b = 0, 1
while a < 10:
  print('a=',a,'b=',b)
  a, b = b, a+b

a= 0 b= 1
a= 1 b= 1
a= 1 b= 2
a= 2 b= 3
a= 3 b= 5
a= 5 b= 8
a= 8 b= 13


In [30]:
#Otra forma de imprimir los valores de a y b
a, b = 0, 1
while a < 10:
  print(f'a={a} b={b}')
  a, b = b, a+b

a=0 b=1
a=1 b=1
a=1 b=2
a=2 b=3
a=3 b=5
a=5 b=8
a=8 b=13


### Ciclo for

In [31]:
words = ['gato', 'ventana', 'entusiasmo']
for w in words:
  print(w, len(w))

gato 4
ventana 7
entusiasmo 10


In [32]:
for i in range(5):
  print(i)

0
1
2
3
4


In [33]:
for i in range(len(words)):
  print(i,words[i])

0 gato
1 ventana
2 entusiasmo


In [34]:
for i,w in enumerate(words):
  print(i,w)

0 gato
1 ventana
2 entusiasmo


## Condicional if, else

In [35]:
x = -34

if x < 0:
  x = 0
  print('Numero negativo cambiado a cero')
elif x == 0:
  print('cero')
elif x == 1:
  print('Uno')
else:
    print('numero positivo')


Numero negativo cambiado a cero


In [36]:
#Para este ejemplo crearemos un diccionario 
alumnos = {'Alma': 'activa', 'Juan': 'inactivo', 'Pedro': 'activa'}
for alumno, estatus in alumnos.copy().items():
    if estatus == 'inactivo':
        del alumnos[alumno]

In [37]:
alumnos

{'Alma': 'activa', 'Pedro': 'activa'}

In [38]:
for n in range(2, 10):
  for x in range(2, n):
    if n % x == 0:
      print(n, 'es igual a ', x, '*', n//x)
      break
  else:         #Este else corresponde al ciclo for, no al if... es una forma de decir lo que se debe hacer cuando se rompe el ciclo... 
    print(n, 'es primo')
     

2 es primo
3 es primo
4 es igual a  2 * 2
5 es primo
6 es igual a  2 * 3
7 es primo
8 es igual a  2 * 4
9 es igual a  3 * 3


In [39]:
for num in range(2, 10):
  if num % 2 == 0:
    print(f"{num} es par")
    continue
    
  print(f"{num} es impar")

2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


# Defininendo  Funciones

In [49]:
def fib(n):    # write Fibonacci series up to n
  """Print a Fibonacci series up to n."""
  a, b = 0, 1
  while a < n:
    print(a, end=' ') #el argumento end previene que haya un cambio de linea. 
    a, b = b, a+b

In [62]:
fib100=fib(10)

0 1 1 2 3 5 8 

In [64]:
print(fib100)

None


In [65]:
#La misma función pero ahora regresando una lista con el resultado
def fib2(n):  # return Fibonacci series up to n
  """Return a list containing the Fibonacci series up to n."""
  result = []
  a, b = 0, 1
  while a < n:
    result.append(a)    # see below
    a, b = b, a+b
 
  return result

In [66]:
fib100=fib2(100)

In [67]:
fib100

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

In [80]:
#funcion con 3 argumentos de entrada y dos de salida. 
def raices(a,b,c):
  raiz=math.sqrt(b**2-4*a*c)
  return (-b+raiz)/2,(-b-raiz)/2

#Función con 3 argumentos de entrada, uno de ellos opcional ya que tiene un valor por defecto, y dos argumentos de salida
def raices2(b,c,a=1):
  raiz=math.sqrt(b**2-4*a*c)
  return (-b+raiz)/2,(-b-raiz)/2
  

In [81]:

raices(1,0,-25)

(5.0, -5.0)

In [82]:

raices2(0,-25)

(5.0, -5.0)

# Arreglos de Numpy
(ver https://numpy.org/doc/stable/user/quickstart.html)

In [92]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [93]:
print(a.shape,a.ndim,a.dtype.name,a.size)

(15,) 1 int64 15


In [94]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [95]:
print(a.shape,a.ndim,a.dtype.name,a.size)

(3, 5) 2 int64 15


In [96]:
type(a)

numpy.ndarray

In [97]:
a = np.array([2, 3, 4])
b = np.array([1.2, 3.5, 5.1])

In [98]:
a

array([2, 3, 4])

In [99]:
b

array([1.2, 3.5, 5.1])

In [100]:
a = np.array(1, 2, 3, 4)

TypeError: ignored

In [105]:
a = np.array([1, 2, 3, 4]) 

In [106]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [107]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [108]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [110]:
np.empty((2, 3)) 

array([[2.52868647e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [117]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [118]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [120]:
arr=np.linspace(0, 10, num=5)
np.sort(arr)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [122]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [123]:
a

array([1, 2, 3, 4])

In [124]:
b


array([5, 6, 7, 8])

In [126]:
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [127]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])